### ISSUE TITLE
/Token not working in Chrome and FireFox

### ISSUE THREAD

**Issue by DavRojas** [DavRojas/RoommateApp#1]
When trying to log in and register in Chrome or FireFox you get a error 400.  However, it works in IE and ME right now.

**Comment by cclally** [comment]
I think I figured out the problem. I'll try and do some testing when I get home tonight. Might need to send a refresh token on login refresh if there isn't a valid token passed that occurs when the user isn't recognised as a "member" or higher role.



Sent from TypeApp<http://www.typeapp.com/r>

On Oct 24, 2016, at 10:58 PM, DavRojas <notifications@github.com<mailto:notifications@github.com>> wrote:

When trying to log in and register in Chrome or FireFox you get a error 400. However, it works in IE and ME right now.

**Comment by DavRojas** [comment]
Waiting for some confirmation that the issue is fixed before I close this issue.
